"""Reporting agent.

Consolidates recon + vuln-analysis output into a single structured Markdown
report: metadata, an executive summary, an open-services table, and the ranked
findings with references.
"""

from __future__ import annotations

from dataclasses import dataclass


def _severity(cvss: float) -> str:
    if cvss >= 9.0:
        return "Critical"
    if cvss >= 7.0:
        return "High"
    if cvss >= 4.0:
        return "Medium"
    if cvss > 0.0:
        return "Low"
    return "None"


@dataclass
class ReportingAgent:
    def render_markdown(self, recon_result: dict, analysis: dict) -> str:
        target = analysis.get("target") or recon_result.get("target") or "unknown"
        summary = analysis.get("summary", {})
        lines: list[str] = []

        lines.append(f"# Red Team Findings — {target}")
        lines.append("")
        lines.append(f"- **Target:** {target}")
        if analysis.get("matched_scope"):
            lines.append(f"- **Authorized scope entry:** {analysis['matched_scope']}")
        if analysis.get("scanned_at"):
            lines.append(f"- **Scanned:** {analysis['scanned_at']}")
        lines.append("")

        lines.append("## Executive Summary")
        lines.append("")
        lines.append(f"- Open services enumerated: **{summary.get('open_services', 0)}**")
        lines.append(f"- Findings: **{summary.get('findings', 0)}**")
        lines.append(
            f"- Findings with a public exploit: "
            f"**{summary.get('with_public_exploit', 0)}**"
        )
        max_cvss = summary.get("max_cvss", 0.0)
        lines.append(f"- Highest severity: **{_severity(max_cvss)}** (CVSS {max_cvss})")
        lines.append("")

        lines.append("## Open Services")
        lines.append("")
        lines.append("| Host | Port | Service | Product | Version |")
        lines.append("|------|------|---------|---------|---------|")
        for host in recon_result.get("hosts", []):
            for p in host.get("ports", []):
                if p.get("state") != "open":
                    continue
                lines.append(
                    f"| {host.get('address', '')} "
                    f"| {p.get('port', '')}/{p.get('protocol', '')} "
                    f"| {p.get('service', '') or ''} "
                    f"| {p.get('product', '') or ''} "
                    f"| {p.get('version', '') or ''} |"
                )
        lines.append("")

        findings = analysis.get("findings", [])
        lines.append("## Findings (ranked by exploitability)")
        lines.append("")
        if not findings:
            lines.append("_No known CVEs matched the enumerated services._")
            lines.append("")
        for i, f in enumerate(findings, 1):
            sev = _severity(f["cvss"])
            exploit = "yes" if f["exploit_available"] else "no"
            lines.append(
                f"### {i}. {f['cve']} — {f['title']}"
            )
            lines.append("")
            lines.append(
                f"- **Severity:** {sev} (CVSS {f['cvss']}) · "
                f"**Public exploit:** {exploit}"
            )
            lines.append(
                f"- **Affected:** {f['product']} {f['version']} "
                f"on {f['host']}:{f['port']}/{f['protocol']} ({f['service']})"
            )
            for ref in f.get("references", []):
                lines.append(f"- Reference: {ref}")
            lines.append("")

        lines.append("---")
        lines.append(
            "_Generated by vantage. Enumeration and analysis only — no "
            "exploitation was performed._"
        )
        lines.append("")
        return "\n".join(lines)
